# Generated by Django 3.0.7 on 2020-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
        ('tag', '0001_initial'),
        ('client', '0002_auto_20200605_1725'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clients',
            field=models.ManyToManyField(blank=True, to='client.Client', verbose_name='clients'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(blank=True, to='project.Project', verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='users',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='users'),
        ),
    ]
