# Generated by Django 3.0.7 on 2020-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('customuser', '0003_customuser_timesheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='task.Task', verbose_name='taches'),
        ),
    ]
