# Generated by Django 3.0.7 on 2020-06-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
        ('tag', '0001_initial'),
        ('client', '0002_auto_20200605_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='description')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='client')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='project')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='tags')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='user')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projects',
                'ordering': ('name',),
            },
        ),
    ]
