# Generated by Django 3.0.7 on 2020-06-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('name',), 'verbose_name': 'timesheet', 'verbose_name_plural': 'timesheets'},
        ),
    ]
