# Generated by Django 3.0.7 on 2020-06-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20200605_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
    ]
