# Generated by Django 3.0.7 on 2020-06-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_tasks'),
        ('task', '0004_auto_20200610_1642'),
        ('client', '0008_client_tasks'),
        ('timesheet', '0003_auto_20200605_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='client',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='project',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='refer_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_timesheet_client', to='client.Client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='refer_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_timesheet_project', to='project.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='refer_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_timesheet_task', to='task.Task', verbose_name='task'),
        ),
    ]
