# Generated by Django 3.0.7 on 2020-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FF0000', max_length=8),
        ),
    ]
