# Generated by Django 3.0.7 on 2020-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='estimated duration'),
        ),
    ]
