# Generated by Django 3.0.7 on 2020-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200610_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
