# Generated by Django 3.0.7 on 2020-06-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='description'),
        ),
    ]
