# Generated by Django 3.0.7 on 2020-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_auto_20200611_1110'),
        ('project', '0009_project_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timesheets',
            field=models.ManyToManyField(blank=True, to='timesheet.Timesheet', verbose_name='timesheets'),
        ),
    ]
