# Generated by Django 3.0.7 on 2020-06-12 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200611_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 7, 49, 39, 719159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 7, 49, 39, 719135, tzinfo=utc)),
        ),
    ]
