# Generated by Django 3.0.7 on 2020-06-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200612_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
