# Generated by Django 3.0.7 on 2020-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='close_date',
            field=models.DateField(blank=True),
        ),
    ]
