# Generated by Django 3.0.7 on 2020-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20200615_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='close_date',
            field=models.DateField(null=True),
        ),
    ]
