# Generated by Django 3.0.7 on 2020-06-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('refer_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_user_lient', to='client.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('name',),
            },
        ),
    ]
